name: atticusthecorgi
favicon: null
layout_spectrum: 0.8023563919123262
typography_spectrum: 0.49204568727873266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6102022300474346
  lightness: 0.022883223369717598
  saturation: 0.5667188668157905
  rhythmicContrast: 0.813301423098892
purpose: []
